# Generated by Django 5.2.9 on 2025-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional unique username (can be used for profile URL later)', max_length=150, null=True, unique=True),
        ),
    ]
